@startuml UC03 - Gestion des Avis

left to right direction
skinparam style strictuml
skinparam backgroundColor White
skinparam shadowing false

actor Client as C
actor Vendeur as V

rectangle "Gestion des Avis" {
    ' === Client ===
    (Consulter les avis) as UC1
    (Donner un avis) as UC2

    
    ' === Vendeur ===
    (Consulter mes avis recus) as UC5
    (Masquer un avis) as UC6
}

' === Associations Client ===
C -- UC1
C -- UC2

' === Associations Vendeur ===
V -- UC5



' === Include Vendeur ===
UC5 <.. UC6 : <<extend>>

@enduml